defaultEntryPoint = ["http", "https"]
logLevel = "INFO"

[api]
  entrypoint = "dashboard"

[entryPoints]
    [entryPoints.dashboard]
        address = ":8080"
    [entryPoints.dashboard.auth]
        [entryPoints.dashboard.auth.basic]
            users = ["admin:$apr1$mrWAMDUN$XjHtyxxSGLRIEl..S4SnG0"]

    [entryPoints.http]
        address = ":80"
#        [entryPoints.http.redirect]
#            entryPoint = "https"

    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

#[acme]
#email = "vishaals2000@gmail.com"
#storage = "acme.json"
#entryPoint = "https"
#onHostRule = true
#    [acme.httpChallenge]
#    entryPoint = "http"
#
[docker]
domain = "http://localhost:80"
watch = true
network = "web"